<head runat="server">

	<asp:contentplaceholder ID="cphHeader" runat="server" visible="true"></asp:contentplaceholder>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Use iconogen.com to generate favicons -->
	<!-- Favicon - Apple Icons and Windows Icons -->
	<link href="/SiteFiles/XXXX/css/images/favicon.ico" rel="icon" type="image/x-icon" />

	<link rel="shortcut icon" href="/SiteFiles/XXXX/css/images//favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" sizes="57x57" href="/SiteFiles/XXXX/css/images//apple-touch-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/SiteFiles/XXXX/css/images//apple-touch-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/SiteFiles/XXXX/css/images//apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/SiteFiles/XXXX/css/images//apple-touch-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/SiteFiles/XXXX/css/images//apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/SiteFiles/XXXX/css/images//apple-touch-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/SiteFiles/XXXX/css/images//apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/SiteFiles/XXXX/css/images//apple-touch-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/SiteFiles/XXXX/css/images//apple-touch-icon-180x180.png">
	<link rel="icon" type="image/png" href="/SiteFiles/XXXX/css/images//favicon-16x16.png" sizes="16x16">
	<link rel="icon" type="image/png" href="/SiteFiles/XXXX/css/images//favicon-32x32.png" sizes="32x32">
	<link rel="icon" type="image/png" href="/SiteFiles/XXXX/css/images//favicon-96x96.png" sizes="96x96">
	<link rel="icon" type="image/png" href="/SiteFiles/XXXX/css/images//android-chrome-192x192.png" sizes="192x192">
	<meta name="msapplication-square70x70logo" content="/SiteFiles/XXXX/css/images//smalltile.png" />
	<meta name="msapplication-square150x150logo" content="/SiteFiles/XXXX/css/images//mediumtile.png" />
	<meta name="msapplication-wide310x150logo" content="/SiteFiles/XXXX/css/images//widetile.png" />
	<meta name="msapplication-square310x310logo" content="/SiteFiles/XXXX/css/images//largetile.png" />


	<!-- Bootstrap -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<!-- Fonts -->
	<!-- Add Font Script Here -->

	<!-- Main Stylesheet -->
	<link href="/SiteFiles/XXXX/css/master.css" rel="stylesheet" type="text/css" />

	<!-- Flexbox Grid Stylesheet -->
	<link href="/SiteFiles/XXXX/css/flexboxgrid.css" rel="stylesheet" type="text/css" />

	<asp:ContentPlaceHolder ID="cphAnalytics" runat="server" visible="true"></asp:ContentPlaceHolder>

	<!-- Modernizer Flexbox JS -->
	<script src="/SiteFiles/XXXX/js/moderizr.flexbox.min.js"></script>

</head>
