<header>
    <div class="logo-wrap">
    	<a class="logo-link" href="/home">
      <!-- <img class="" src="" alt="" /> -->
    	</a>
    </div>
    <!-- Nav Class: sw-nav-default | flex-nav -->
    <nav class="sw-nav-default">
      <button type="button" id="drawer-toggle" class="pull-right">
        Open Menu
        <span></span>
      </button>
    	<asp:ContentPlaceHolder ID="cphMainMenu" runat="server" visible="true"></asp:ContentPlaceHolder>
    </nav>
</header>